# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-21 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=128, verbose_name='\u81ea\u5b9a\u4e49ID')),
                ('buget_type', models.CharField(choices=[('expressway', '\u9ad8\u901f\u516c\u8def\u7ecf\u8425'), ('build', '\u9ad8\u901f\u516c\u8def\u5efa\u8bbe'), ('cunstruction', '\u65bd\u5de5\u4f01\u4e1a'), ('investment', '\u8d44\u4ea7\u6295\u8d44')], max_length=30)),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9884\u7b97\u8bf4\u660e')),
                ('standard', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9884\u7b97\u5b9a\u989d')),
                ('edit_dept', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7f16\u5236\u90e8\u95e8')),
                ('approve_dept', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5ba1\u6838\u90e8\u95e8')),
                ('account_item', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8d22\u52a1\u79d1\u76ee')),
                ('add_user', models.CharField(blank=True, max_length=36, null=True, verbose_name='\u6dfb\u52a0\u7528\u6237')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('bk1', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u75281')),
                ('bk2', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u75282')),
                ('bk3', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u75283')),
                ('bk4', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u75284')),
            ],
            options={
                'verbose_name': '\u9884\u7b97\u79d1\u76ee',
                'verbose_name_plural': '\u9884\u7b97\u79d1\u76ee',
            },
        ),
    ]
