# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-21 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugetitem',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6dfb\u52a0\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='bugetitem',
            name='buget_type',
            field=models.CharField(choices=[('expressway', '\u9ad8\u901f\u516c\u8def\u7ecf\u8425'), ('build', '\u9ad8\u901f\u516c\u8def\u5efa\u8bbe'), ('cunstruction', '\u65bd\u5de5\u4f01\u4e1a'), ('investment', '\u8d44\u4ea7\u6295\u8d44')], max_length=30, verbose_name='\u7c7b\u522b'),
        ),
    ]
