# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-03 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5355\u4f4d\u540d\u79f0')),
                ('description', models.CharField(max_length=20, verbose_name='\u5355\u4f4d\u63cf\u8ff0')),
                ('parentID', models.IntegerField(null=True, verbose_name='\u4e0a\u7ea7\u5355\u4f4d')),
                ('leftID', models.IntegerField(null=True, verbose_name='\u5de6\u5e73\u7ea7\u5355\u4f4d')),
                ('rightID', models.IntegerField(null=True, verbose_name='\u53f3\u5e73\u7ea7\u5355\u4f4d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('bk', models.CharField(max_length=255, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u7ec4\u7ec7\u673a\u6784',
                'verbose_name_plural': '\u7ec4\u7ec7\u673a\u6784',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='\u804c\u52a1'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u627e\u56de\u5bc6\u7801')], max_length=10, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Org', verbose_name='\u6240\u5c5e\u5355\u4f4d'),
        ),
    ]
