# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-03 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170903_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='bk',
            field=models.CharField(max_length=255, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
