# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-22 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20180320_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenlane',
            name='addtime',
            field=models.DateField(default='', max_length=30, null=True, verbose_name='\u586b\u62a5\u65f6\u95f4'),
        ),
    ]
